In [ ]:
#pip install pandas  scikit-learn

#ML model  sai kit learn

In [1]:
# step 1 - module need import 
#80 train 20 test 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [11]:
df=pd.read_csv("std_dataset.csv")

df.head()

   StudyHours  Marks
0         1.0     27
1         1.2     31
2         1.2     28
3         1.3     33
4         1.4     25

In [30]:
# 2 column 1 input 2 output StudyHours Marks
X=df[["StudyHours"]] # input = 2d output = 1d 
y=df["Marks"]

In [31]:
# step 3 = data split 80 training 20 per testing 
#80 20 
X_train, X_test, y_train, y_test = train_test_split(
    
    X, y, test_size=0.2, random_state=42
)
#1,2,3,4,5 =4.5 as test ,1,2,3 traing 
#y=mx+c =accuracy  correct and incorrct accura=40

In [14]:
y_train

55     66
88    100
26     38
42     52
69     86
     ...
60     77
71     97
14     38
92    100
51     66
Name: Marks, Length: 80, dtype: int64

In [15]:
X_train

    StudyHours
55         5.7
88         8.8
26         2.8
42         4.2
69         7.2
..         ...
60         6.3
71         7.4
14         2.0
92         9.3
51         5.4

[80 rows x 1 columns]

In [16]:
X_test

    StudyHours
83         8.3
53         5.6
70         7.4
45         4.5
44         4.4
39         3.9
22         2.6
80         8.0
10         1.7
0          1.0
18         2.3
30         3.4
73         7.6
33         3.6
90         9.1
4          1.4
76         7.8
77         7.9
12         1.9
31         3.5

In [17]:
y_test

83     99
53     68
70     87
45     57
44     59
39     57
22     41
80     90
10     33
0      27
18     32
30     48
73     92
33     51
90    100
4      25
76     92
77     91
12     44
31     51
Name: Marks, dtype: int64

In [ ]:

model=LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(X_test) # input testing 80 train 20 

print(y_pred)

In [ ]:
print("actual data")
print(y_test)

print("predict data")

print(y_pred) #100  // data set // unseen data // predication

In [ ]:
newresult=pd.DataFrame({
    "StudyHours":[3]
})
marks=model.predict(newresult)
print("myresult",marks[0])

In [ ]:
#r2 score 0.78 =78 true 22false 
#actual-predication = output y 
from sklearn.metrics import r2_score

r2=r2_score(y_test,y_pred)

print(r2) #98 2 false result //98 80

In [ ]:
from sklearn.metrics import mean_absolute_error

mae=mean_absolute_error(y_test,y_pred)
print(mae)

In [ ]:
from sklearn.metrics import mean_squared_error

mse=mean_squared_error(y_test,y_pred)
print(mse)

# RMSE  =mse root = RMSE

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(rmse)

In [ ]:
#  api - ci/cd - live server deploy 
# joblib - model save and load 
# github action /jenkins 
# docker 
# github 
# live server = rendor-server install 
# yml 
# req.txt  -lib install 
#fastapi and uvicorn server 
# netlify 
# model -frontend = AI -website enter u rmarks = website predication 

#github -repo 1= gmail login 
# rendor and netlify  2-3 lect=ai website  3model Ai enginner